# Dependencies
markdown:         kramdown
highlighter:      Rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Tang Yuxiang
tagline:          'A CVer'
description:      '一二三四五'
url:              https://hyde.getpoole.com
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://yuxiangtang.github.io/

plugins: [jekyll-paginate, jekyll-gist, jekyll-sitemap, jekyll-seo-tag]
