# Dependencies
markdown:         kramdown
highlighter:      Rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Tang Yuxiang
tagline:          'A CVer'
description:      '北京邮电大学计算机学院 E-mail:tangyx2020@outlook.com'
url:              https://blog.csdn.net/it2153534
baseurl:          /

author:
  name:           'TangYuxiang'
  url:            https://blog.csdn.net/it2153534

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/YuxiangTang

plugins: [jekyll-paginate, jekyll-gist, jekyll-sitemap, jekyll-seo-tag]
